import React, { useEffect, useState } from "react";
import { useRouter } from 'next/router'
import { useDispatch, useSelector } from "react-redux";
import {requireAuthentication} from "../requireAuthentication"
import Cookies from 'js-cookie';
import Moralis from 'moralis'
import {
  getProducts,
  deleteProduct,
  addProduct,
  ApproveProduct,
  RejectProduct,
} from "../../redux/actions/productActions";
import Swal from "sweetalert2";
import "../components/GlobalVariable"
import { Table } from "reactstrap";
import Navsidebar from "../components/Navsidebar";
import Link from "next/dist/client/link";
import { useMoralis, useMoralisFile } from "react-moralis";
import Web3 from "web3";
import ProductTable from "../components/Product-Component/ProductTable";
import Head from "next/dist/shared/lib/head";

const Products = () => {
  const dispatch = useDispatch();
  const allProductsData = useSelector((state) => state.Products);
  const { loading, error, products } = allProductsData;

  // LOAD DATA
  useEffect(() => {
    dispatch(getProducts());
  }, []);

  const router = useRouter();

  return (

    <div className="container-fluid py-4">
          <Head>
            <title>Product</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
        
        <Navsidebar/>
        
      <div className="row">
        <div className="col-12">
          <div className="card mb-4">
            <div className="card-header pb-0">
              <div className="row">
                <div className="col-6 d-flex align-items-center">
                  <h6 className="mb-0">Product Table</h6>
                </div>
                <div className="col-6 text-end">
                  <Link href={{ pathname: '/Product/SaveProduct'}}>
                    <a className="btn bg-gradient-dark mb-0"><i className="fas fa-plus"></i>&nbsp;&nbsp;Add New Product</a>
                  </Link>
                </div>
              </div>
            </div>
            <div className="card-body px-0 pt-0 pb-2">
              <ProductTable ProductData={products} error={error} loading={loading}/>
            </div>
          </div>
        </div>
      </div>
    </div>
         
  );
};

export default Products;

export const getServerSideProps = requireAuthentication(context => {
    return {props: {}}
})