import React, { useEffect, useState } from "react";
import { useRouter } from 'next/router'
import { useDispatch, useSelector } from "react-redux";
import {requireAuthentication} from "../requireAuthentication"
import "../components/GlobalVariable"
import Navsidebar from "../components/Navsidebar";
import Link from "next/dist/client/link";
import ProductActivityTable from "../components/Product-Activity/ProductActivityTable";
import Custompaginations from "../components/Pagination";
import { getPApaging } from "../../redux/actions/paActions";
import { Input } from "reactstrap";

const Bills = () => {
  const dispatch = useDispatch();
  const allProductsData = useSelector((state) => state.Pas);
  const { loading, error, pas } = allProductsData;

  const router = useRouter()
  const {Page, Search}  = router.query;

  const handleSearch = (e) => {
    if (e.key === 'Enter') {
      location.href = "?Search=" + e.target.value;
    }
  };

  var Pagess = 0;
  var TotalDisplayed = 10;
  var sear = "";

  if(Page == null){
    Pagess = 1;
  }else{
    Pagess = Page;
  }

  if(Search != null){
    sear = Search;
  }

  // LOAD DATA
  useEffect(() => {
    dispatch(getPApaging(Pagess, TotalDisplayed, sear, false));
  }, []);

  return (

    <div className="container-fluid py-4">
        <title>Bills</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={global.icon} />
        
        <Navsidebar/>
        
      <div className="row">
        <div className="col-12">
          <div className="card mb-4">
            <div className="card-header pb-0">
              <div className="row">
                <div className="col-9 d-flex align-items-center">
                  <h5 className="mb-0">Admin Bills</h5>
                </div>
                <div className="col-3 text-end">
                  <div className="input-group mb-4">
                    <span className="input-group-text"><i className="fa-solid fa-magnifying-glass"></i></span>
                    <Input onKeyDown={handleSearch}  placeholder="Search by Address" defaultValue={sear != "" ? sear : null} className="form-control"/>
                  </div>
                </div>
              </div>
            </div>
            <div className="card-body px-0 pt-0 pb-2">
              <ProductActivityTable ProductData={pas} error={error} loading={loading}/>
            </div>
          </div>
          <Custompaginations PageNow={Pagess} TotalDisplayed={TotalDisplayed} TotalProduct={pas.intTotalData} isRouterQuery={sear != "" ? true : false}/>
        </div>
      </div>
    </div>
         
  );
};

export default Bills;

export const getServerSideProps = requireAuthentication(context => {
    return {props: {}}
})