import { useState } from "react";
import { useDispatch, useSelector } from "react-redux"
import Swal from "sweetalert2";
import "../components/GlobalVariable";
import {requireAuthentication} from "../requireAuthentication"
import Navsidebar from "../components/Navsidebar";

const EditProfile = () => {
    const dispatch = useDispatch();
    const allProfileData = useSelector((state) => state.Profile);
    // const { loading, error, profile } = allProfileData;

    //HANDLE CHANGE 
    const handleChange = (e) => {
        let data = { ...userInput };
        data[e.target.name] = e.target.value;
        setUserInput(data);
    };

    //INPUT DATA
    const [userInput, setUserInput] = useState({
        picture:"",
        username:"",
        email:"",
        bio:"",
        token:"",
    });

    const handleSubmit = (e) => {
        e.preventDefault();
        if (
            (userInput.picture === "",
            userInput.username === "",
            userInput.email === "",
            userInput.username === "",
            userInput.bio === "",
            userInput.token === "")
            ) {
                return false;
            }
            dispatch(
                addUsers({
                    picture: userInput.picture,
                    username: userInput.username,
                    email: userInput.email,
                    bio: userInput.bio,
                    token: userInput.token,
                })
            );
            Swal.fire(
                "Profile Berhasil Disimpan",
                "success"
            );

            setUserInput({
                picture:"",
                username:"",
                email:"",
                bio:"",
                token:"",
            });
        };

    return (
        <div className="container-fluid py-4">
        <title>Profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.png" />
        {/* <Layout></Layout> */}
        <Navsidebar></Navsidebar>
      
      <div className="container-fluid mt--6">
      <div className="row">
        <div className="col-lg-4">
          <div className="card card-profile">
            <img src="/header.jpg" alt="Image placeholder" className="card-img-top"/>
            <div className="row justify-content-center">
              <div className="col-lg-3 order-lg-2">
                <div className="card-profile-image">
                  <a href="#">
                    <img src="/man.png" className="rounded-circle"/>
                  </a>
                </div>
              </div>
            </div>
            
            <div className="card-body pt-0">
              
              <div className="text-center">
                <h5 className="h3">
                  Jessica Jones<span className="font-weight-light">, 27</span>
                </h5>
                <div className="h5 font-weight-300">
                  <i className="ni location_pin mr-2"></i>Bucharest, Romania
                </div>
                <div className="h5 mt-4">
                  <i className="ni business_briefcase-24 mr-2"></i>Solution Manager - Creative Tim Officer
                </div>
                <div>
                  <i className="ni education_hat mr-2"></i>University of Computer Science
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className="col-lg-8">
          <div className="card">
            <div className="card-header">
              <div className="row align-items-center">
                <div className="col-8">
                  <h3 className="mb-0">Edit profile </h3>
                </div>
                
              </div>
            </div>
            <div className="card-body">
              <form>
                <h6 className="heading-small text-muted mb-4">User information</h6>
                <div className="pl-lg-4">
                  <div className="row">
                    <div className="col-lg-6">
                      <div className="form-group">
                      <label className="form-control-label" for="input-full-name">Fullname</label>
                        <input
                        type="input"
                        className="form-control"
                        placeholder="enter your name"
                        name="fullname"
                        // onChange={handleChange}
                        // value={userInput.txtFullName}
                      />
                      </div>
                    </div>
                    <div className="col-lg-6">
                      <div className="form-group">
                        <label className="form-control-label" for="input-username">Username</label>
                        <input
                        type="input"
                        className="form-control"
                        placeholder="enter your name"
                        name="username"
                        // onChange={handleChange}
                        // value={userInput.txtUsername}
                      />
                      </div>
                    </div>
                  </div>
                  <div className="row">
                    <div className="col-lg-6">
                      <div className="form-group">
                        <label className="form-control-label" for="input-email">Email Address</label>
                        <input
                        type="input"
                        className="form-control"
                        placeholder="enter your email"
                        name="email"
                        // onChange={handleChange}
                        // value={userInput.txtEmail}
                      />
                      </div>
                    </div>
                    <div className="col-lg-6">
                      <div className="form-group">
                        <label className="form-control-label" for="input-Password">Password</label>
                        <input
                        type="password"
                        className="form-control"
                        placeholder="enter password"
                        name="password"
                        // onChange={handleChange}
                        // value={userInput.txtPassword}
                      />
                      </div>
                    </div>
                  </div>
                  <div className="row">
                    <div className="col-lg-6">
                      <div className="form-group">
                        <label className="form-control-label" for="input-KTP">Upload KTP</label>
                        <input
                        type="file"
                        className="form-control"
                        placeholder="choose file"
                        name="KTP"
                        // onChange={handleChange}
                        // value={userInput.NIK_photo}
                      />
                      </div>
                    </div>
                  </div>
                  <div className="row">
                    <div className="col-lg-6">
                      <div className="form-group">
                        <label className="form-control-label" for="input-NIK">NIK/Induk kependudukan</label>
                        <input
                        type="input"
                        className="form-control"
                        placeholder="enter your id number"
                        name="email"
                        // onChange={handleChange}
                        // value={userInput.NIK}
                      />
                      </div>
                    </div>
                    <div className="col-lg-6">
                      <div className="form-group">
                        <label className="form-control-label" for="input-tokenID">Token ID</label>
                        <input
                        type="input"
                        className="form-control"
                        // placeholder={profile.Token_ID}
                        name="token ID"
                        // onChange={handleChange}
                      />
                      </div>
                    </div>
                  </div>
                </div>
                <hr className="my-4" />
                {/* <!-- Address --> */}
                <h6 className="heading-small text-muted mb-4">Contact information</h6>
                <div className="pl-lg-4">
                  {/* <div className="row">
                    <div className="col-md-12">
                      <div className="form-group">
                        <label className="form-control-label" for="input-address">Address</label>
                        <input id="input-address" className="form-control" placeholder="Home Address" value="Bld Mihail Kogalniceanu, nr. 8 Bl 1, Sc 1, Ap 09" type="text"/>
                      </div>
                    </div>
                  </div> */}
                  <div className="row">
                    <div className="col-lg-4">
                      <div className="form-group">
                        <label className="form-control-label" for="input-twitter">Twitter</label>
                        <input
                        type="input"
                        className="form-control"
                        placeholder="@example"
                        name="twitter"
                        // onChange={handleChange}
                        // value={userInput.Twitter}
                      />
                      </div>
                    </div>
                    <div className="col-lg-4">
                      <div className="form-group">
                        <label className="form-control-label" for="input-instagram">Instagram</label>
                        <input
                        type="input"
                        className="form-control"
                        placeholder="@example"
                        name="instagram"
                        // onChange={handleChange}
                        // value={userInput.Instagram}
                      />
                      </div>
                    </div>
                    <div className="col-lg-4">
                      <div className="form-group">
                        <label className="form-control-label" for="input-website">Website</label>
                        <input
                        type="input"
                        className="form-control"
                        placeholder="www@example.id"
                        name="website"
                        // onChange={handleChange}
                        // value={userInput.Website}
                      />
                      </div>
                    </div>
                  </div>
                </div>
                {/* <hr className="my-4" />
                <h6 className="heading-small text-muted mb-4">About me</h6> */}
                <div className="pl-lg-4">
                  <div className="form-group">
                    <label className="form-control-label">About me</label>
                    <textarea
                        type="input"
                        className="form-control"
                        placeholder="write about you"
                        name="bio"
                        // onChange={handleChange}
                        // value={userInput.Bio}
                      />
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
      </div>
      </div>
        )
    }

    export default EditProfile;

    export const getServerSideProps = requireAuthentication(context => {
      return {props: {}}
  })