import Head from "next/head";
import Layout from "./components/Layout";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Admin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Layout></Layout>
        <div className="container-fluid py-4">

      <section className="article">
        <h1>Welcome Admin</h1>
      </section>
      </div>
    </div>
  );
}
