import Head from "next/head";
import Layout from "./components/Layout";
import Navsidebar from "./components/Navsidebar";

export default function Home() {
  
      return (
        <div>
          <Head>
            <title>Dashboard</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
            <Navsidebar></Navsidebar>
            
            <div className="container-fluid py-4">

            <section className="article">
              <h1>Welcome Admin</h1>
            </section>
          </div>
        </div>
      );
}
