import React, { useState } from "react";
// import { ethers } from "ethers";
// import "./App.css";
import { Button, Card } from "react-bootstrap";
import "bootstrap/dist/css/bootstrap.min.css";
  
const Login = () => {
  
  // usetstate for storing and retrieving wallet details
  const [data, setdata] = useState({
    address: "",
    Balance: "",
    Username: "",
  });
  
  // Button handler button for handling a
  // request event for metamask
  const btnhandler = () => {
  
    // Asking if metamask is already present or not
    if (window.ethereum) {
  
      // res[0] for fetvhing a first wallet
      window.ethereum
        .request({ method: "eth_requestAccounts" })
        .then((res) => accountChangeHandler(res[0]));
    } else {
      alert("install metamask extension!!");
    }
  };
  
  // getbalance function for getting a balance in
  // a right format with help of ethers
  const getbalance = (saldo) => {
    // Requesting balance method
    window.ethereum
      .request({ 
        method: "eth_getBalance", 
        params: [saldo, "latest"] 
      })
      .then((balance) => {
        // Setting balance
        setdata({
          Balance: ethers.utils.formatEther(balance),
        })
      });
  };

  const getusername = () => {
    // Requesting balance method
   if (window.ethereum) {

      window.ethereum
      .request({ method: "eth_accounts"})
      .then((res) => accountChangeHandler(res[0]));
   }
     else {
      alert("install metamask extension!!");
    }
  };

  const accountChangeHandler = (account) => {
    // Setting an address data
    setdata({
      address: account,
    });
  
    // Setting a balance
    getbalance(account);

    getusername(account);
  };

 
  return (
    <div className="bg-login">
      <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.png" />

    <div class="container mt--8 pb-5">
      <div class="row justify-content-center">
        <div class="col-lg-5 col-md-7">
          <div class="coba-geser border-0 mb-0 coba-geser">
            
            <div class="card-body px-lg-5 py-lg-5">
              <div class="btn-wrapper text-center">
                <span class="btn-inner--icon"><img width={"300px"} src="logo.png"/></span>
              </div>
              <div class="text-center text-muted mb-4">
                <small class="textnih">Login with your Wallet </small>
              </div>
                <div class="text-center">
                  <button class="btnconnect" onClick={btnhandler} variant="primary">
                  <img width={"50px"} src="image5.png"/>Connect with Metamask</button>
                </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div className="App">
      {/* Calling all values which we 
       have stored in usestate */}
  
      <Card className="text-center">
        <Card.Header>
          <strong>Address: </strong>
          {data.address}
        </Card.Header>
        <Card.Body>
          <Card.Text>
            <strong>Balance: </strong>
            {data.Balance}
          </Card.Text>
          <Card.Text>
            <strong>Username: </strong>
            {data.Username}
          </Card.Text>
          <Button onClick={btnhandler} variant="primary">
            Connect to wallet
          </Button>
        </Card.Body>
      </Card>
    </div>
    </div>
    
  );
}
  
export default Login;